language: go
go: 1.13

os:
        - linux
        - osx

jobs:
        include:
                name: "build"
                script: go build
                name: "unit tests"
                script: go test -v ./...
