language: go
go: 1.13

os:
        - linux
        - osx

jobs:
        include:
                - name: "go build"
                  script: go build
                - name: "go test"
                  script: go test -v ./...
